### ISSUE TITLE
Is it possible to run the solution locally, like F5 from VS.NET?

### ISSUE THREAD

**Issue by harrchen88** [mspnp/microservices-reference-implementation#100]
I have a docker for windows and can build the solution successfully.  It will be nice to be able to run the solution from VS.NET like any other web application.  Right, I get exceptions for null location.

**Comment by ferantivero** [comment]
thanks for sharing, 

could you please share the exception you are receiving and if that is executing a particular step or action from this Reference Implementation? 

Regarding F5 experience, we couldn't agree more with you and we've already created issue to track all the efforts related to this #45

**Comment by ferantivero** [comment]
please let us close this for now due to inactivity. Please feel free to re-open if necessary.
