### ISSUE TITLE
ACS->AKS

### ISSUE THREAD

**Issue by Stellaleigh** [mspnp/microservices-reference-implementation#104]
Now that AKS is GAed, can we please use AKS instead of ACS-engine in this repo?

**Comment by ferantivero** [comment]
good catch @Stellaleigh, please let me add a reference to [the original item](#80) we created for this.

**Comment by MikeWasson** [comment]
This is on our backlog - should work fine but requires some testing and updated deployment steps.

Closing as dup of #80
