### ISSUE TITLE
Scheduler service should handle 204 from package service

### ISSUE THREAD

**Issue by MikeWasson** [mspnp/microservices-reference-implementation#108]
The [createPackageAsync](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/services/PackageServiceCallerImpl.java#L75) method should handle 204 (No Content) response from package service.

Note that 204 will not include the package in the response body.

**Comment by ferantivero** [comment]
done https://github.com/mspnp/microservices-reference-implementation/commit/8c5d884ff225be9eb410f71723f6d8f17034cb04
