### ISSUE TITLE
Potentially dangerous async code in the scheduler

### ISSUE THREAD

**Issue by fsimonazzi** [mspnp/microservices-reference-implementation#117]
The service callers are implemented using a pattern that seems problematic (it would definitely be so if mapped literally to .net)

For example the package service (same pattern is used for other services). The [entry method](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/services/PackageServiceCallerImpl.java#L75) performs an [asynchronous call](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/services/PackageServiceCallerImpl.java#L77-L80) which returns a future, and then [registers an asynchronous callback](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/services/PackageServiceCallerImpl.java#L82-L91) on that future to [update an instance variable](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/services/PackageServiceCallerImpl.java#L28) and then this instance variable [is returned as the result of the method](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/services/PackageServiceCallerImpl.java#L97).

Two main concerns:
* The value set by the callback is used without knowing that the callback was executed at all.
* The logic relies on shared state (not even closures, but instance variables) so depending on how this caller is shared this could be a problem. 
** Given that these callers [are initialized statically](https://github.com/mspnp/microservices-reference-implementation/blob/master/src/shipping/scheduler/src/com/fabrikam/dronedelivery/deliveryscheduler/scheduler/DeliveryRequestEventProcessor.java#L40-L51) these instances will be shared unless Akka is serializing processing (which would be problematic in itself).
** Also, sharing state across threads without synchronization is usually problematic

**Comment by magrande** [comment]
This Reference Implementation has been completely reworked. I will proceed to close the issue.
