### ISSUE TITLE
Callback is added to newly created completed future

### ISSUE THREAD

**Issue by fsimonazzi** [mspnp/microservices-reference-implementation#118]
The delivery processor creates a completed future only to attach a callback on completion. Since it's already completed the callback will run right away. Since this is the "async" method, it will be scheduled for execution in a different thread; that's a useful side effect, but if that's the goal of this construct there are more direct and explicit mechanisms to schedule work in the thread pool.

```
		CompletableFuture.completedFuture(deliverySchedule).whenCompleteAsync((ds, error) -> {
			if (ds == null) {
				Log.error("Failed Delivery");
				superviseFailureAsync(deliveryRequest, ServiceName.DeliveryService,
						error == null ? "Unknown error" : ExceptionUtils.getStackTrace(error).toString())
								.thenAcceptAsync(result -> Log.debug(result));
			} else {
				Log.info("Completed Delivery", ds.toString());
			}

		});
```

**Comment by ferantivero** [comment]
If I recall properly this service has been replaced in the past for a new one. Closing as per this information. 

Please let's reopen if required.
