### ISSUE TITLE
Error running Ingestion build image to produce jar file

### ISSUE THREAD

**Issue by keithfree** [mspnp/microservices-reference-implementation#121]
I am running on Win10 Enterprise v1809 with Docker for Windows v18.09.2 installed and configured for linux containers. 

I am able to successfully build the Ingestion service's build image (`openjdk_and_mvn-build:8-jdk`), whose base image is `openjdk:8-jdk`. 

When I run this step:
```PowerShell
$INGESTION_PATH="${SOURCE_CODE_ROOT}\src\shipping\ingestion"
docker run -it -v ${INGESTION_PATH}:/sln openjdk_and_mvn-build:8-jdk
```

I get the following error:
> **Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter**
> 
> Results :
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:21 min
> [INFO] Finished at: 2019-03-06T13:58:30Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project Ingestion: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd /sln && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /sln/target/surefire/surefirebooter2156255563599099968.jar /sln/target/surefire/surefire2972241147860250331tmp /sln/target/surefire/surefire_02516224541232345229tmp

**Comment by keithfree** [comment]
By adding the below into the `<build><plugins>` section of the Ingestion pom.xml, I am able to run `docker run -it -v ${INGESTION_PATH}:/sln openjdk_and_mvn-build:8-jdk` and see the tests pass and the  jar files created in the `\src\shipping\ingestion` directory. 
```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.3</version>
      </plugin>
```

Unfortunately, the resulting image throws an exception when Kubernetes tries running it as a container.

> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/usr/share/dronedelivery/Ingestion-1.0.0.jar!/BOOT-INF/lib/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/usr/share/dronedelivery/Ingestion-1.0.0.jar!/BOOT-INF/lib/slf4j-jdk14-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/usr/share/dronedelivery/Ingestion-1.0.0.jar!/BOOT-INF/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
> **Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from jar:file:/usr/share/dronedelivery/Ingestion-1.0.0.jar!/BOOT-INF/lib/slf4j-simple-1.7.12.jar!/). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.SimpleLoggerFactory**
> 	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:389)
> 	at org.springframework.util.Assert.isInstanceOf(Assert.java:327)
> 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:273)
> 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:97)
> 	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:230)
> 	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:209)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
> 	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
> 	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
> 	at com.fabrikam.dronedelivery.ingestion.IngestionApplication.main(IngestionApplication.java:17)
> 	... 8 more
>

**Comment by ferantivero** [comment]
thanks for reporting this @keithfree, please let us check with the team

cc/ @francischeung

**Comment by ferantivero** [comment]
thanks again for reporting this issue @keithfree, checked with the team and it seems to be known issue. The good news are there are on going efforts in a revamped version for this Reference Implementation. 

Please stay tuned, soon you should see some updates around here.

**Comment by ferantivero** [comment]
@keithfree we've just updated with lot of new features in case you want to give a try. I'm closing it for now. Please fell free to re-open it if you face any issues.
