### ISSUE TITLE
Can not find COSMOSDB_COL_NAME 

### ISSUE THREAD

**Issue by chhtw** [mspnp/microservices-reference-implementation#127]
There is no definition for $COSMOSDB_COL_NAME at microservices-reference-implementation
/deployment.md line247 
`     --set cosmosDb.collectionName=$COSMOSDB_COL_NAME \`

**Comment by ferantivero** [comment]
you're right @chhtw, we'd appreciate to see a PR from you with this addition 😸

By the way, If I am not wrong, when not defined it should default to ```packages```

**Comment by chhtw** [comment]
I run the script and the $COSMOSDB_COL_NAME is empty. I am stuck at this step.
Can I set the ` $COSMOSDB_COL_NAME=packages ` and run it again?

**Comment by ferantivero** [comment]
thanks for the quick turn around @chhtw, yes please let's define the env var as you mentioned.

**Comment by ferantivero** [comment]
this been solved from [here](https://github.com/mspnp/microservices-reference-implementation/commit/c55e0883ab9466a8473f98f376987e8eedbef00f).
