### ISSUE TITLE
Cannot deploy delivery service

### ISSUE THREAD

**Issue by fawohlsc** [mspnp/microservices-reference-implementation#128]
I followed [Deploying the Reference Implementation](https://github.com/mspnp/microservices-reference-implementation/blob/master/deployment.md) and I am stuck in **Deploy the Delivery service**:

`helm install $HELM_CHARTS/delivery/ \
     --set image.tag=0.1.0 \
     --set image.repository=delivery \
     --set dockerregistry=$ACR_SERVER \
     --set identity.clientid=$DELIVERY_PRINCIPAL_CLIENT_ID \
     --set identity.resourceid=$DELIVERY_PRINCIPAL_RESOURCE_ID \
     --set cosmosdb.id=$DATABASE_NAME \
     --set cosmosdb.collectionid=$COLLECTION_NAME \
     --set keyvault.uri=$DELIVERY_KEYVAULT_URI \
     --set reason="Initial deployment" \
     --namespace backend \
     --name delivery-v0.1.0`

When I invoke the command it results in this error message: 
_"Error: azureidentities.aadpodidentity.k8s.io "delivery-identity" already exists"_

I tried to delete _delivery-identity_ by replacing _DELIVERY_PRINCIPAL_RESOURCE_ID_, _DELIVERY_PRINCIPAL_CLIENT_ID_ in _/charts/delivery/templates/delivery-identity.yaml_ and the invoking _kubectl delete -f delivery-identity.yaml_, but this results in  _azureidentities.aadpodidentity.k8s.io "delivery-identity" not found_ - not sure why it says "delivery-identity" exits, but then it is not found...

**Comment by fawohlsc** [comment]
The problem was an outdated helm version - v2.13.1 works for me. Probably it's about how helm handles hooks for Custom Resource Definitions with azureidentities.aadpodidentity.k8s.io

**Comment by fawohlsc** [comment]
Request to add workaround to documentation

**Comment by ferantivero** [comment]
thanks for reporting this @fawohlsc, and also for sharing [your workaround here](https://github.com/mspnp/microservices-reference-implementation/issues/128#issuecomment-489039256) 😸 

Please stay tuned a solution for this is going to be released soon.

**Comment by ferantivero** [comment]
the latest release should take care of it. Please let us close this for now and feel free to re-open if necessary.
