### ISSUE TITLE
[Deployment] Improve monitoring section fluentd-ES

### ISSUE THREAD

**Issue by ferantivero** [mspnp/microservices-reference-implementation#131]
Azure Monitor for Containers is now being prescribed as main Monitoring solution for the Reference Implementation. 

Fluentd-ES section can be now removed or add some note to clarify how these two monitoring solutions will live together.

**Comment by squillace** [comment]
Please, before doing this ensure that you've consulted with not only the AKS PM, but also App Plat Upstream and GBB. Whilst Azure Monitor is fine -- OSS software here remains better for users at the moment (though that won't remain so!). 

Only make this move if you've consulted with PM and customers first. But then, if you HAVE, go for it! (My two cents.)

**Comment by ferantivero** [comment]
thanks for the feedback @squillace,  please let me cc part of the team

cc/ @MikeWasson @dragon119

**Comment by squillace** [comment]
Best approach is to note that there are both OSS solutions that you can manage (the current instructions) and also integrated solutions that Microsoft can manage for you (Azure container monitoring). As always, different people will choose different _implementations_ for the same feature, which is what good patterns are all about.

**Comment by ferantivero** [comment]
hi @squillace, long time no talking 👋 . This is just a quick follow up to let you know that we're re-thinking some of our reference implementations for AKS and this is one of them.

Please let me /cc @doodlemania2 to see if we can baseline this elsewhere or keep it as part of this specific one somehow.

**Comment by ferantivero** [comment]
team has made the decision of retiring this integration with Fluentd-ES because this is currently out of date. However, we keep encouraging the users to use OOS solutions in particular this one for Fluentd-ES from [our docs](https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring).
