### ISSUE TITLE
Getting 503 service unavailable when sending a request

### ISSUE THREAD

**Issue by Srini1905** [mspnp/microservices-reference-implementation#138]
Followed all the steps, when validating by posting a delivery request, getting a 503 status code.
Any troubleshooting steps would be appreciated.

**Comment by ferantivero** [comment]
thanks for your feedback @Srini1905, it's definitely a missing section in the Reference Implementation. Please let me share this with the team.

In the meantime, could you please execute the following commands and share their output?

```bash
# list the overall status of the applications
helm ls

# drill down a bit the nginx-ingress status
helm status nginx-ingress

# drill down a bit the delivery app status
helm status delivery-v0.1.0-dev

# check the external delivery ingress config
kubectl get Ingress/delivery-v0.1.0-dev-ingress -n backend-dev -o yaml

#  print the URL
echo $"https://$EXTERNAL_INGEST_FQDN/api/deliveryrequests"
```

/cc @MikeWasson

**Comment by Srini1905** [comment]
Thanks for getting back @ferantivero. Please find attached the output of the commands requested.
[k8stroubleshooting.txt](https://github.com/mspnp/microservices-reference-implementation/files/3700414/k8stroubleshooting.txt)

**Comment by ferantivero** [comment]
thanks for sharing this info @Srini1905, after some investigation we found that a possible way of getting this reprod is by deleting the ingestion service.

That said, could you please execute the following extra commands and share their output?

```bash
# list all the service objects (here ingestion services should be listed)
kubectl get svc -n backend-dev

# drill down a bit the ingestion app status 
helm status ingestion-v0.1.0-dev

# if ingestion pod is not running, lets try to dig a bit deeper
kubectl -n backend-dev logs $(kubectl -n backend-dev get pods -l app.kubernetes.io/name=ingestion -o name)

# nginx controller logs (shouldn't be required but trying to save an extra roundtrip here)
kubectl logs nginx-ingress-controller-7657f59d86-kqc88 -n ingress-controllers
```

**Comment by Srini1905** [comment]
Thanks @ferantivero. I think we are getting close. Problem seems to be the ingestion service (please see attached). After following the above steps I am getting http 202 status code which I guess is expected! 
When checking the request status though I am seeing http 404 (I tried different pickup times)

[k8stroubleshooting10-8-2019.txt](https://github.com/mspnp/microservices-reference-implementation/files/3705462/k8stroubleshooting10-8-2019.txt)

**Comment by ferantivero** [comment]
First and foremost, we strongly recommend you to edit your previous comment and delete the txt file, as this is leaking some of your secrets.

Regarding http404, please let's double check how the GET request url is getting composed. Please find below an example, and notice `mydelivery` is just a placeholder that must be replaced with the deliveryId you received in the response body from the previous step/POST:

`curl "https://$EXTERNAL_INGEST_FQDN/api/deliveries/3a3c34e7-b818-4a93-9764-0e627dc39879" --header 'Accept: application/json' -k -i`
 
On the other hand, I'm glad to see you started receiving http202 when POSTing, and yes it's the expected response https status. I think we found the culprit 😸, and it wasn't the ingestion service but the ingestion pod in a CrashLoopBackOff state. From `helm status ingestion-v0.1.0-dev`

```
ingestion-v010-dev-85557688bc-cg78m  0/1    CrashLoopBackOff  634       2d7h
```

From the logs, what we can see is that for some reason the $AI_IKEY was empty. We'd recommend to look for the rest of the services just in case they're running into the same problem.

I'm closing this issue for now, but please don't hesitate on re-open this one or open another one in case more support is needed.

**Comment by Srini1905** [comment]
thanks. Thought I removed all keys, anyways deleted the attachment.
I am seeing an error in the Dronedeliveryservice. I will re deploy the service and see if the problem goes away, otherwise I will create a new issue.

Thanks for all your help!
