### ISSUE TITLE
Latest Helm version is not working with the the commands listed

### ISSUE THREAD

**Issue by myaesubi** [mspnp/microservices-reference-implementation#147]
Hi,
I'm encountering couple of issues with the Helm commands.
I have installed Helm version 3.1 and the following commands and parameter does not exist in new version.

**helm init --service-account tiller**

**helm install stable/nginx-ingress --name nginx-ingress-dev --namespace ingress-controllers --set rbac.create=true --set controller.ingressClass=nginx-dev**

I think also the helm repo add command is missing, since it does not recognize **stabe/nginx-ingress** in above command as well.

Thanks,
Mohammad

**Comment by ferantivero** [comment]
thanks for your feedback @myaesubi,

please let's just give a try by installing helm 2.14.2 or lower for now:

```
DESIRED_VERSION=v2.14.2;curl -L https://git.io/get_helm.sh | bash
```

I'm closing this issue for now, but please do not hesitate in re-open or create new issues if you need more support.

**Comment by myaesubi** [comment]
thank you @ferantivero. downgrading works. 

Cheers,
Mohammad
