### ISSUE TITLE
Multiple issues with the deployment document

### ISSUE THREAD

**Issue by magdysalem2** [mspnp/microservices-reference-implementation#148]
I was able to deploy the example successfully. Thank you for the detail instruction. I am assuming "master" branch is the latest code so I encounter the following issues
1- ingress-controllers name space creation command is missing
2- droneschedule deploy template need update to fix "ports" indent 
3- Delivery deploy template  need update to fix "ports" indent 
4- workflow value missing resources values. Although I apply the quota but it still required by Helm.

P.S it will be great to update the code to use Helm 3

**Comment by ferantivero** [comment]
Thanks for your feedback @magdysalem2, glad to hear you were able to get it deployed.

Please note you can find an advanced version in master-adv branch, you will get extra features like Cluster Autoscaler and HPA. We’re in process of getting them officially documented soon.

Helm 3 is definitely in radar 😺, some time in January most probably.

Please let us keep this open while we solve couple of issues you raised here.

Thanks again,

**Comment by ferantivero** [comment]
quick update on this: helm 3 is still on the works.

**Comment by ferantivero** [comment]
points 2nd and 3rd are solved by now, not quite sure about the 4th one. Regarding 1st, helm2 creates this for you.

Closing this for now. Please feel free to re-open or open a new one in case more support is needed.

**Comment by ferantivero** [comment]
hey there! just to let you know that helm 3 charts are now released 😸
