### ISSUE TITLE
Deny all ingress and egress traffic step in dev instructions fails

### ISSUE THREAD

**Issue by kristianjaeger** [mspnp/microservices-reference-implementation#178]
command suggested in instructions:
kubectl apply -f $K8S/k8s-deny-all-non-whitelisted-traffic-dev.yaml

output:
Deployment failed. Correlation ID: cbb8f60b-ac02-4f8e-9eb8-2d2f8b7b17ef. {
  "error": {
    "code": "AzureFirewallRuleInvalidIpAddressOrRangeFormat",
    "message": "AzureFirewallRule jrbfeonuxfsz6-r7njpag7lfheo..TunnelFrontCommToK8sApiServer: Invalid IP address value or range or Service Tag AzureCloud..",
    "details": []
  }
}

Thanks.

**Comment by ferantivero** [comment]
thanks for reporting this @kristianjaeger, 

could you please execute again the deployment for the `azuredeploy-firewall.json` and please ensure you have a value in the env var named `SERVICETAGS_LOCATION`.

**Comment by kristianjaeger** [comment]
Thanks @ferantivero .  I can try that when I have time.  I already tore down the cluster but could recreate it.

**Comment by kristianjaeger** [comment]
Hmm, @ferantivero I just tried this again and the command seems to just set the variable to an empty string:
Running on OS X Mojave:
`export SERVICETAGS_LOCATION=$(az account list-locations --query "[?name=='${LOCATION}'].displayName" -o tsv | sed 's/[[:space:]]//g')`

Yields:
echo $SERVICETAGS_LOCATION
empty string (hard to copy and paste that for a good visual)

Should it just be the region location string like "West US 2"?  Thanks.

**Comment by kristianjaeger** [comment]
I think I found the issue. It looks like for location one should use the location ID instead of the name. So, "westus2" instead of "West US 2". Cheers.

**Comment by kristianjaeger** [comment]
The step succeeded after I made that change to location ID. Cheers.

**Comment by ferantivero** [comment]
awesome! thanks for sharing it 😸 

Please let me close this issue for now.
