### ISSUE TITLE
Reference implementation is not updated to Helm, Azure AD version etc

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/microservices-reference-implementation#180]
Hello team, since its only reference implementation available from Microsoft, it should be up to date with respect to AKS features, Here we are still using Helm 2, Legacy AD implementation etc.
Request you to take this on priority and update the reference implementation as per the latest features.

**Comment by ferantivero** [comment]
thanks for reporting this @nitinkhandelwal26 we're currently using Helm3 in the charts from the `advanced` version.

On the other hand, we might upgrade to Helm 3 the `basic` version as well as the Azure AD integration in this repo in the future. This is not confirmed though.

Please stay tuned.

cc/ @doodlemania2

**Comment by neilpeterson** [comment]
@nitinkhandelwal26 we are going to get the helm version updated. Apologies for the delay.

**Comment by v-fearam** [comment]
It was updated to helm 3 this repo. Sorry for the delay.

**Comment by ckittel** [comment]
Going to close this issue as the body of work has changed with the inclusion of the AKS Baseline, and [superseeded](https://github.com/mspnp/aks-fabrikam-dronedelivery).  Minimal maint. will continue on this repo.
