### ISSUE TITLE
Any reference to statefulset implementation

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/microservices-reference-implementation#181]
hello team,

Is there any reference implementation available from Patterns and Practice team on stateful sets implementation? I am unable to find any neither in this repo nor anywhere else.
Request you to please redirect.

Regards

**Comment by ferantivero** [comment]
thanks for this inquiry @nitinkhandelwal26, please let us share the following guide using Azure Service Fabric to close this:
https://docs.microsoft.com/en-us/azure/architecture/service-fabric/migrate-from-cloud-services

Additionally, we're planning for future Reference Implementations and this topic might be taken into account for AKS as well.

/cc @doodlemania2
