### ISSUE TITLE
pipeline-deployment-issue

### ISSUE THREAD

**Issue by rambabu0063** [mspnp/microservices-reference-implementation#185]
Hi Team,
I am trying to deploy pipeline using script but its throwing an error.
<img width="480" alt="pipeline-deploy-issue" src="https://user-images.githubusercontent.com/57993345/90142606-3315f300-dd9a-11ea-9b5c-b7bcc6aee539.PNG">

could you please help us to resolve this issue

**Comment by nitinkhandelwal26** [comment]
@ferantivero Request you to please help here...

**Comment by ferantivero** [comment]
thanks for reporting this @rambabu0063 as a first step I'd suggest to inspect `src/shipping/package/azure-pipeline.yml` and try to spot some syntax issue or if any variable was not set like `azureSubscription`, `azureContainerRegistry` or `azureContainerRegistryName`.

Since the pipeline was created, you could also try to manually kickoff the `package-ci` pipeline using the Azure Pipelines UI to see if you can get a more detailed error from there.

**Comment by rambabu0063** [comment]
thank you for your response @ferantivero 

I have  ran the pipeline manually, Build got success. But I am facing another issue to hit the vsrm api url
<img width="945" alt="400-error-aks-pipeline" src="https://user-images.githubusercontent.com/57993345/90252094-8badc480-de5c-11ea-9678-8537afbda318.PNG">

I have validated the  json azure-pipelines-cd-0.json . its available on local repo. and token is also getting generated but I am getting 400 response.

**Comment by ferantivero** [comment]
@rambabu0063 glad to hear you got it working and the build passed. For the `400` response back I plan to keep this issue open as it will require more investigation.

In the meantime, you could take another route to get it working which is to use the Azure Pipeline UI, and import cd pipeline from `${DELIVERY_PATH}/azure-pipeline-cd-0.json`

**Comment by rambabu0063** [comment]
Hi Team,

I was trying to deploy pipeline using json location but its getting failed.
could you please help us to resolve this issue
<img width="480" alt="pipeline-deploy-issue" src="https://user-images.githubusercontent.com/57993345/90394295-0cb0ca00-e0b0-11ea-9d8d-2e4a1aa90492.PNG">

**Comment by ferantivero** [comment]
@rambabu0063 could you please remove the secrets from your cd pipeline and share the json with us?

**Comment by rambabu0063** [comment]
Hi @ferantivero ,

please find the attached json file.

[azure-pipelines-cd-0.zip](https://github.com/mspnp/microservices-reference-implementation/files/5090576/azure-pipelines-cd-0.zip)

**Comment by ferantivero** [comment]
I've just checked it and at first glance it seems the `qa`, `staging` and `production` variables are not set. Could you please quickly check on your pipeline, set those variables and see if that improve and change the error messages you are getting in there?

**Comment by rambabu0063** [comment]
I have deployed in Dev only. 
do we need to deploy solution in all (qa,staging and prod)

**Comment by ferantivero** [comment]
if your intention is to create a pipeline that is solely responsible for deploying to a single stage (e.g. `dev`), you will have create another different pipeline than this which is designed to work with multiple stages.  

On the other hand, what you could do is to configure this pipeline as required and after it gets properly created/running you could just indicate to deploy to a single stage like `dev`, `qa` or `staging`. If I recall properly, you can't directly deploy to `prod` as it'd require both `qa` and `staging` to get successfully deployed first.

**Comment by ckittel** [comment]
@rambabu0063 -- we are going to close/archive this issue.  If you want to continue the conversation, you're welcome to open it back up.  Hopefully we've been able to help you along here, thanks @ferantivero for all the guidance delivered on this!
