### ISSUE TITLE
Tiller is removed but still given instruction to apply Tiller

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/microservices-reference-implementation#186]
https://github.com/mspnp/microservices-reference-implementation/blob/master/deploymentCICD.md

This shows instruction Helm 2 installation, please update.

**Comment by ferantivero** [comment]
thanks for sharing this @nitinkhandelwal26 `basic` version is using Helm 2 and that's the reason why you might find some of those instructions still out there. If that were the case, please feel free close this issue. Otherwise, could you please share with us the line from deployment instructions?
