### ISSUE TITLE
add Pod resource request/limit

### ISSUE THREAD

**Issue by ferantivero** [mspnp/microservices-reference-implementation#33]
this issue is just to address the following PR: https://github.com/mspnp/microservices-reference-implementation/pull/26

**Comment by dragon119** [comment]
Configure resource limit for scheduler no other services.

**Comment by ferantivero** [comment]
will keep this open for now. We have new numbers from Load Testing executions. We should want to update them soon.

**Comment by ferantivero** [comment]
latest release is taking of it for all the services. Closing it for now.
