### ISSUE TITLE
provide other ways to get our RI deployed

### ISSUE THREAD

**Issue by ferantivero** [mspnp/microservices-reference-implementation#45]
Since now we documented how to get our RI deployed step by step. It would be great if we provide with other ways to deploy fast and easier in next version:
1. helm chart
2. shell script for creation and clean up.
3. one shot kubectl apply

**Comment by dragon119** [comment]
Make it as F5 experience with Jenkins pipeline.

**Comment by ferantivero** [comment]
we've just updated the reference implementation. I'm closing it for now as we are providing a very streamline process for deployment in this new version using ARM and Helm. We're also working on enabling Azure Pipelines experience.
