### ISSUE TITLE
add horizontal pod autoscaling

### ISSUE THREAD

**Issue by ferantivero** [mspnp/microservices-reference-implementation#46]

**Comment by dragon119** [comment]
Evaluate HPA supported by Kube

**Comment by dragon119** [comment]
Looks like this task[https://pnp.visualstudio.com/DroneDelivery/_workitems?id=6089&_a=edit] has some info about HPA.

**Comment by ferantivero** [comment]
evaluated and implemented 💪 

Closing this issue for now.
