### ISSUE TITLE
es-fluentd linked configs are not compatible

### ISSUE THREAD

**Issue by ferantivero** [mspnp/microservices-reference-implementation#50]
we found at least the following incompatibilities:
* fluentd es default host name mismatch    
* missing es x-pack
* fluentd-es namespace(s) missmatch

**Comment by ferantivero** [comment]
agree!

Taking into account the recent treatment we gave to l5d, should we consider to address this in similar fashion?

**Comment by dragon119** [comment]
Create an issue in their repo and add a link to that issue here.
