### ISSUE TITLE
Events should be named in simple past tense. An Event happended in the past.

### ISSUE THREAD

**Issue by CESARDELATORRE** [mspnp/microservices-reference-implementation#67]
I see this event named `DeliveryStatusEvent`:
https://github.com/mspnp/microservices-reference-implementation/blob/master/src/bc-shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Models/DeliveryStatusEvent.cs

Events (any kind, Domain Events, Integration Events, etc.) should be named in simple past tense. An event is something that has happened in the past.
As Greg Young highlights here:
http://codebetter.com/gregyoung/2010/04/11/what-is-a-domain-event/
An event is something that has happened in the past. 
**All events should be represented as verbs in the past tense** such as CustomerRelocated, CargoShipped, etc.

Also, see here:
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation

**Comment by ferantivero** [comment]
thanks for sharing this @CESARDELATORRE, please let us take a look at this

**Comment by MikeWasson** [comment]
Thanks for the feedback - the file you referenced is the event typename, the actual events are defined [here](https://github.com/mspnp/microservices-reference-implementation/blob/9365a5ae8e272bf64f509c8ca5af76f4b0bc92be/src/bc-shipping/delivery/Fabrikam.DroneDelivery.Common/DeliveryEventType.cs)

**Comment by CESARDELATORRE** [comment]
Then event # 3, 4 and 5 should be changed to something in simple past tense, because their name is like a Status more than an Event that happened.

**Comment by francischeung** [comment]
How about the follow renames?

DroneHeadingToPickupLocation -> HeadedToPickup
InTransit -> HeadedToDropoff
DeliveryComplete -> Completed
