### ISSUE TITLE
l5d support for multiple namespaces

### ISSUE THREAD

**Issue by ferantivero** [mspnp/microservices-reference-implementation#69]
Linkerd supports multiple namespaces. We could implement some of the following approaches to get servicemesh config ready for bc-shipping:
1. ship custom yaml for l5d 
2. add some instructions on how to modify servicemesh.yml
3. add some instructions on how to remove the integration with l5d (temporary) 

For now to workaround this, please use this configuration instead:

EDIT:
```bash
wget https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd.yml && \
sed -i "s#/default#/bc-shipping#g" linkerd.yml && \
kubectl apply -f linkerd.yml
```

**Comment by cfarre** [comment]
I vote for option 1 or 2. service mesh is an important feature for our guidance. it is a simple fix just modify the yaml.

**Comment by cfarre** [comment]
@francischeung @ferantivero 

I tested this script and it does not work. Basically there are default  entries that cannot be replaced. the only default entries that can be replaced are the entries that are in the dtab. I changed the entries manually and it worked

entries that should be replaced

 - protocol: http
      label: outgoing
      dtab: |
        /srv        => /#/io.l5d.k8s/bc-shipping/http;
        /host       => /srv;
        /svc        => /host;



    - protocol: http
      label: incoming
      dtab: |
        /srv        => /#/io.l5d.k8s/bc-shipping/http;
        /host       => /srv;
        /svc        => /host;

entries that cannot be replaced

    interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: incoming
          service: l5d

   interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode

**Comment by ferantivero** [comment]
as discussed offline, we plan to invest some cycles on option #2.

**Comment by ferantivero** [comment]
just edited the workaround, so it does not replace some unnecessary default values.
