### ISSUE TITLE
Improve monitoring yaml file 

### ISSUE THREAD

**Issue by dragon119** [mspnp/microservices-reference-implementation#77]
Provide a better yaml file for monitoring and setup instructions.

**Comment by ferantivero** [comment]
we've got some progress around in this PR: https://github.com/mspnp/microservices-reference-implementation/pull/23

**Comment by cfarre** [comment]
@ferantivero @dragon119 @francischeung 

In which namespace should monitoring be provisioned. the requirements are pods for daemonset, grafana, kubestats and Prometheus server

**Comment by ferantivero** [comment]
@cfarre personally I'd pretty much love to see Prometheus and Grafana in a separate namespace (e.g. monitoring).

We've already deployed linkerd-viz in another namespace and it works. 

cc @francischeung

**Comment by cfarre** [comment]
@ferantivero @mabsimms @francischeung 

it is going to be deployed in monitoring namespace as per your recommendation

**Comment by ferantivero** [comment]
we've just updated the reference implementation. I'm closing it for now as we enable Azure Monitor fro Containers and using AppInsights in this new version.
