### ISSUE TITLE
Add -o json to command

### ISSUE THREAD

**Issue by buzzfrog** [mspnp/microservices-reference-implementation#83]
A small enhancement to command
export ACR_SERVER=$(az acr show -g $RESOURCE_GROUP -n $ACR_NAME --query "loginServer")

Add
export ACR_SERVER=$(az acr show -g $RESOURCE_GROUP -n $ACR_NAME --query "loginServer" **-o json**)

**Comment by ferantivero** [comment]
@buzzfrog thanks for your suggestion I've tested it but I don't pretty much differences in the output. 

Please note that this commend is asking for a specific value of loginServer. 

Please let me know if I am missing here.

cc @MikeWasson

**Comment by buzzfrog** [comment]
It depends of which default output format you have. az configure. 
I have table, and then it doesn't work.
/dag

**Comment by ferantivero** [comment]
oh I see it now :point_up_2: 

Thanks again for this again!

**Comment by MikeWasson** [comment]
PR #105 fixes this by specifying -o tsv
