### ISSUE TITLE
Design principles not followed

### ISSUE THREAD

**Issue by propellingbits** [mspnp/microservices-reference-implementation#97]
Looks like design principles are staying limited to documents only and not getting implemented in code. Why are we using deliveryRepository in DeliveriesController?

Please do not say it is a mock implementation. Even interns can write good mocks. We need to show real life code so that other devs can learn and take home the right approach.

Thanks,
Mandeep

**Comment by MikeWasson** [comment]
The delivery repository isn't a mock, it talks to Redis Cache.

**Comment by propellingbits** [comment]
We should not be using repositories in controllers.

**Comment by MikeWasson** [comment]
But why do you consider that an anti-pattern? It's useful to have an abstraction over the data store - you wouldn't want the controller to call Redis directly. And it lets you mock the data store for unit testing.

**Comment by propellingbits** [comment]
Mike,

I think you know this but maybe you have different thoughts - should not we add a (business) service and call repository from there? As controllers are supposed to be just skinny pass-throughs.

**Comment by MikeWasson** [comment]
Ah, OK - I see what you're saying. I agree controllers should be skinny. In this project the services intentionally have little / no business logic, because the focus of this guidance was on things like the interservice communication, data ingestion, data stores, etc.
